<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MozcInput.Protocol</AssemblyName>
    <RootNamespace>MozcInput.Protocol</RootNamespace>
    <AssemblyTitle>Mozc Input Protocol</AssemblyTitle>
    <EnableResoniteReferences>false</EnableResoniteReferences>
  </PropertyGroup>
</Project>
