<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MozcInput</AssemblyName>
    <RootNamespace>MozcInput</RootNamespace>
    <AssemblyTitle>Mozc Input</AssemblyTitle>
    <IsResoniteModProject>true</IsResoniteModProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MozcInput.Protocol\MozcInput.Protocol.csproj" />
    <ProjectReference Include="..\..\tools\MozcInput.Bridge\MozcInput.Bridge.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
